-- Member
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    id INT(10) NOT NULL AUTO_INCREMENT UNIQUE ,
    nickname VARCHAR(20) NOT NULL UNIQUE ,
    email VARCHAR(20) NOT NULL UNIQUE ,
    password VARCHAR(30) NOT NULL,
    CONSTRAINT PRIMARY KEY(ID)
);