-- Member
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    id BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE ,
    nickname VARCHAR(20) NOT NULL UNIQUE ,
    email VARCHAR(20) NOT NULL UNIQUE ,
    password VARCHAR(60) NOT NULL,
    CONSTRAINT PRIMARY KEY(ID)
);