-- Member
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    id BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE ,
    nickname VARCHAR(20) NOT NULL UNIQUE COMMENT '사용자명',
    email VARCHAR(20) NOT NULL UNIQUE COMMENT '이메일',
    password VARCHAR(60) NOT NULL COMMENT '비밀번호',
    role varchar(20) not null COMMENT '권한',
    CONSTRAINT PRIMARY KEY(ID)
);